### ISSUE TITLE
Upgrade the blog to gatsby 4

### ISSUE THREAD

**Issue by sjahl** [broadinstitute/gnomad-blog#107]
This PR is requiring that we upgrade to gatsby 4.0 to resolve a build-time security fix. @rileyhgrant took a quick look at that upgrade and found that it was more than a trivial amount of work.

Creating this issue so that we can appropriately prioritize the work in our backlog.

**Comment by rileyhgrant** [comment]
Related dependabot PR: https://github.com/broadinstitute/gnomad-blog/pull/115
