### ISSUE TITLE
Allow all blog post authors to access the rich text CMS

### ISSUE THREAD

**Issue by rileyhgrant** [broadinstitute/gnomad-blog#147]
Currently, only users with write access to this repository (`gnomad-blog`) can access the admin interface.

We should allow all contributors to blog posts to edit the blog post they have authorship over directly to minimize the amount of converting that needs to happen.

**Comment by rileyhgrant** [comment]
Alternately, a drop in Google Docs -> Markdown kinda thing

**Comment by sjahl** [comment]
I think the plan here is to just add authors to the blog repository when the time comes to write posts. I don't think there's much else that's actionable here.
