### ISSUE TITLE
Netlify CMS is now Decap

### ISSUE THREAD

**Issue by sjahl** [broadinstitute/gnomad-blog#165]
https://www.netlify.com/blog/netlify-cms-to-become-decap-cms/

Came across this while looking at updating our blog deployment. Given that netlify CMS is being developed under a new name (at least...) we should maybe look at what's required to switch and if the new product serves our needs.

**Comment by rileyhgrant** [comment]
As of #164, we are already using the renamed "decap" (specifically this [commit](https://github.com/broadinstitute/gnomad-blog/commit/81ff2691e6e494fa680de4213f7ce9abff736127)). 

This did however lead me to double check one thing and open a quick pr to fix one last issue (I had checked editing existing posts, but creating a new post led to a malformed date in the frontmatter - #167)
